spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tasks_db
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

spring.jpa.hibernate.ddl-auto: update

app:
  allowed-origins: 'http://localhost:4200'
